### ISSUE TITLE
Person creation in LDAP import (Firstname and Surname)

### ISSUE THREAD

**Issue by safestackhq** [SafeStack/ava#107]
Person objects are created when we import identities from LDAP. This however is very primative and the following has not been properly addressed:

1) Only create person for non system accounts (Windows has a load of system accounts that aren't actually people. They should be blacklisted and not have Person objects created for them)
2) Do we pull enough fields from LDAP/AD? We don't currently have a clean firstname and surname to create a Person from. Can we pull this cleanly (changes to model and ldap_interface.py required) or do we need to actually split the display_name field to attempt to generate?

Acceptance criteria:
1) Person only created for non-system accounts
2) Person has first name and surname set that relate to the account

**Comment by wanion** [comment]
I'd be interested to take a look at this later but in AD first name is givenName and last name is sn. You can't safely split displayName because there's no guarantee it will be anything sensible. Given displayName is also the name used by Exchange for a user's mailbox it may be backwards if they like surname first, or may include the organization's name, or any number of other bits of weirdness. Often not even consistently across all accounts. And of course, things could be entirely different in another LDAP based directory (non-AD).

**Comment by safestackhq** [comment]
Thanks :) Will have a look at the import to add the missing fields so we at least have them in the json even if we don't have them imported properly to the Person object yet
